ZOAU: "/zoau/v1.4.0"
PYZ: "/allpython/3.12/usr/lpp/IBM/cyp/v3r12/pyz"
PYZ_VERSION: "3.12"
OEF: /usr/lpp/oef/V1R1M0

environment_vars:
  _BPXK_AUTOCVT: "ON"
  ZOAU_HOME: "{{ ZOAU }}"
  PYTHONPATH: "{{ ZOAU }}/lib/{{ PYZ_VERSION}}:/tmp/lib"
  LIBPATH: "{{ ZOAU }}/lib:{{ PYZ }}/lib:/lib:/usr/lib:."
  PATH: "{{ ZOAU }}/bin:{{ PYZ }}/bin:{{OEF}}/bin:/bin:/var/bin"
  _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
  _TAG_REDIR_ERR: "txt"
  _TAG_REDIR_IN: "txt"
  _TAG_REDIR_OUT: "txt"
  LANG: "C"
  PYTHONSTDINENCODING: "cp1047"


# Environment vars used on AAP
# ZOAU_HOME:/zoau/v1.4.0
# PYTHON_HOME:/allpython/3.12/usr/lpp/IBM/cyp/v3r12/pyz
# OEF_HOME: /usr/lpp/oef/V1R1M0
# PYTHON_VERSION: 3.12
# ansible_python_interpreter: {{ PYTHON_HOME }}/bin/python3
# ansible_pipelining: true
# ansible_scp_extra_args: -O

# environment_vars:
#   _BPXK_AUTOCVT: "ON"
#   PYTHONPATH: "{{ ZOAU_HOME }}/lib/{{ PYTHON_VERSION}}:/tmp/lib/"
#   LIBPATH: "{{ ZOAU_HOME }}/lib:{{ PYTHON_HOME }}/lib:/lib:/usr/lib:."
#   PATH: "{{ ZOAU_HOME }}/bin:{{ PYTHON_HOME }}/bin:{{OEF_HOME:}}/bin:/bin:/var/bin"
#   _CEE_RUNOPTS: "FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"
#   _TAG_REDIR_ERR: "txt"
#   _TAG_REDIR_IN: "txt"
#   _TAG_REDIR_OUT: "txt"
#   LANG: "C"
#   PYTHONSTDINENCODING: "cp1047"